#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 24.1.0-p089
#--------------------------------------------------------------------------------------

quantus  -log_file /home/saul/projects/LF_BG/pvsRunLVS/REF_GEN/REF_GEN_fL_2/svdb/qrc.REF_GEN_fL_2.log -cmd /home/saul/projects/LF_BG/pvsRunLVS/REF_GEN/REF_GEN_fL_2/svdb/qrc.REF_GEN_fL_2.ccl 
