#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 24.1.0-p089
#--------------------------------------------------------------------------------------

quantus  -log_file /home/saul/projects/LF_BG/pvsRunLVS/REF_GEN/REF_V5_fLC/svdb/qrc.REF_V5_fLC.log -cmd /home/saul/projects/LF_BG/pvsRunLVS/REF_GEN/REF_V5_fLC/svdb/qrc.REF_V5_fLC.ccl 
