set -e
set -x

rex -dp_comm_string 1,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexarP4yav np_rMETAL1a::METAL1_cut - rVIA1,1,x rPOLYCONT,1,T rPDIFFCONT_PDIFF_METAL1a,1,T rPDIFFCONT_METAL1a_PNPEMIT5UX5U,1,T rNDIFFCONT_NDIFF_METAL1a,1,T rNDIFFCONT_METAL1a_PNPBASE,1,T - L1T0,1,I

rex -dp_comm_string 2,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexahPsNRa np_rPOLYG3::POLYG3_cut - RNPOLYHNW1V2_rvia,1,z rPOLYG3_PGATE_POLYG3_butt_ovia,1 rPOLYG3_NGATE_POLYG3_butt_ovia,1 rPOLYCONT,1,x rPGATE_POLYG3_ovia,1 rNGATE_POLYG3_ovia,1

rex -dp_comm_string 3,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexaozEHRo np_rMETAL2a::METAL2_cut - rVIA2,1,x rVIA1,1,T - L2T0,1,I

rex -dp_comm_string 4,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexadnNJjP np_rNDIFF::NDIFF_cut - NMOS1V2HVT_msdvia,1,z rNDIFFCONT_NDIFF_PNPBASE,1,T rNDIFFCONT_NDIFF_NTAP,1,T rNDIFFCONT_NDIFF_METAL1a,1,x

rex -dp_comm_string 5,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexagR7yNp np_rNTAP::NTAP_cut - rNW1V2_NTAP_ovia,1 rNDIFFCONT_PNPBASE_NTAP,1,x rNDIFFCONT_NDIFF_NTAP,1,x

rex -dp_comm_string 6,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexa7M6oqy np_rPDIFF::PDIFF_cut - PMOS1V2HVT_msdvia,1,z rPDIFFCONT_PDIFF_PTAP,1,T rPDIFFCONT_PDIFF_PNPEMIT5UX5U,1,T rPDIFFCONT_PDIFF_METAL1a,1,x

rex -dp_comm_string 7,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexaH6kx1y np_rPNPBASE::PNPBASE_cut - PNP5UX5U_bbvia,1,z rNDIFFCONT_PNPBASE_NTAP,1,T rNDIFFCONT_NDIFF_PNPBASE,1,x rNDIFFCONT_METAL1a_PNPBASE,1,x

rex -dp_comm_string 8,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexaKW7EPx np_rPTAP::PTAP_cut - rPW1V2_PTAP_ovia,1 rPSUB_PTAP_ovia,1 rPDIFFCONT_PNPEMIT5UX5U_PTAP,1,x rPDIFFCONT_PDIFF_PTAP,1,x

rex -dp_comm_string 9,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexar9T2aq np_rMETAL3a::METAL3_cut - rVIA3,1,x rVIA2,1,T - L3T0,1,I

rex -dp_comm_string 10,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexaAwjBW7 np_rPNPEMIT5UX5U::PNPEMIT5UX5U_cut - PNP5UX5U_bevia,1,z rPDIFFCONT_PNPEMIT5UX5U_PTAP,1,T rPDIFFCONT_PDIFF_PNPEMIT5UX5U,1,x rPDIFFCONT_METAL1a_PNPEMIT5UX5U,1,x

rex -dp_comm_string 11,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexadrxBLZ np_rPGATE::PGATE_cut - PMOS1V2HVT_mgvia,1,z rPGATE_POLYG3_ovia,1 rPGATE_PGATE_POLYG3_butt_ovia,1

rex -dp_comm_string 12,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexayYXey3 np_rNGATE::NGATE_cut - NMOS1V2HVT_mgvia,1,z rNGATE_POLYG3_ovia,1 rNGATE_NGATE_POLYG3_butt_ovia,1

rex -dp_comm_string 13,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexaf47fRO np_rMETAL5a::METAL5_cut - CMIMS2_METAL5a_cvia,1,z rVIAF2,1,x rVIA4,1,T

rex -dp_comm_string 14,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexacevq19 np_rMETALFa::METALF_cut - rVIAM_TOPMIMS2_METALFa,1,T rVIAF2,1,T

rex -dp_comm_string 15,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexabPlfh9 np_rTOPMIMS2::MIMS_cut - CMIMS2_TOPMIMS2_cvia,1,z rVIAM_TOPMIMS2_METALFa,1,x

rex -dp_comm_string 16,edatools,41629 -V -m -pd -I# -tech /opt/pdk/lf11/PDK_LF11ISi_V1_3_2/pv/qrc/6metal/pvs/typ -no_cut -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CMIMS2_TOPMIMS2_cvia,CMIMS2_METAL5a_cvia:RNPOLYHNW1V2_rvia:PNP5UX5U_bbvia,PNP5UX5U_bevia -Ply np_rPGATE,np_rNGATE -rP res.mod -mp mprexazmkMps np_rMETAL4a::METAL4_cut - rVIA4,1,x rVIA3,1,T

rexmerge -V -N NET -n mprexagR7yNp,mprexaKW7EPx,mprexaAwjBW7,mprexaH6kx1y,mprexa7M6oqy,mprexadnNJjP,mprexadrxBLZ,mprexayYXey3,mprexahPsNRa,mprexarP4yav,mprexaozEHRo,mprexar9T2aq,mprexazmkMps,mprexaf47fRO,mprexabPlfh9,mprexacevq19 -b np_rNTAP::Rnp_rNTAP.dev2,np_rPTAP::Rnp_rPTAP.dev2,np_rPNPEMIT5UX5U::Rnp_rPNPEMIT5UX5U.dev2,np_rPNPBASE::Rnp_rPNPBASE.dev2,np_rPDIFF::Rnp_rPDIFF.dev2,np_rNDIFF::Rnp_rNDIFF.dev2,np_rPGATE::Rnp_rPGATE.dev2,np_rNGATE::Rnp_rNGATE.dev2,np_rPOLYG3::Rnp_rPOLYG3.dev2,np_rMETAL1a::Rnp_rMETAL1a.dev2,np_rMETAL2a::Rnp_rMETAL2a.dev2,np_rMETAL3a::Rnp_rMETAL3a.dev2,np_rMETAL4a::Rnp_rMETAL4a.dev2,np_rMETAL5a::Rnp_rMETAL5a.dev2,np_rTOPMIMS2::Rnp_rTOPMIMS2.dev2,np_rMETALFa::Rnp_rMETALFa.dev2 -l ,,,,,,,,,L1T0,L2T0,L3T0,,,, np_rNTAP.res,np_rPTAP.res,np_rPNPEMIT5UX5U.res,np_rPNPBASE.res,np_rPDIFF.res,np_rNDIFF.res,np_rPGATE.res,np_rNGATE.res,np_rPOLYG3.res,np_rMETAL1a.res,np_rMETAL2a.res,np_rMETAL3a.res,np_rMETAL4a.res,np_rMETAL5a.res,np_rTOPMIMS2.res,np_rMETALFa.res

